# Generated by Django 4.2.2 on 2023-07-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
